name: Auto-assign issues

on:
  issues:
    types: [opened, reopened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign issue
        uses: pozil/auto-assign-issue@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: Nek-12
          numOfAssignee: 1
          allowSelfAssign: true
